WAREHOUSE_SIZE = (20, 12)
BATTERY_CRITICAL = 12
BATTERY_LOW = 25
BATTERY_CONSUMPTION_MOVING = 0.8
BATTERY_CONSUMPTION_IDLE = 0.05
BATTERY_CHARGE_RATE = 4.5
ROBOT_SPEED = 1.2

BASE_ORDER_SPAWN_PROBABILITY = 0.5
MIN_ORDER_PROBABILITY = 0.1
ORDER_PROBABILITY_DECAY = 0.1
ORDER_COOLDOWN = 1
MAX_ACTIVE_ORDERS = 8

MIN_ASSIGNMENT_SCORE = 0.5

THRESHOLD_DISTANCE = 0.2